### ISSUE TITLE
CSG.cube doesn't create cube

### ISSUE THREAD

**Issue by bobc** [omgwtfgames/csg.cs#4]
CSG.cube doesn't generate the right result

https://github.com/omgwtfgames/csg.cs/blob/master/Assets/CSG/Plugins/CSG/CSG.cs#L333
Replacing 

                            c.x + (r.x * (2 * (((i & 1) > 0) ? 1 : 0) - 1)),
                            c.y + (r.y * (2 * (((i & 2) > 0) ? 1 : 0) - 1)),
                            c.z + (r.z * (2 * (((i & 4) > 0) ? 1 : 0) - 1))),
with

                            c.x + (r.x * (2 * (((v[0][i] & 1) > 0) ? 1 : 0) - 1)),
                            c.y + (r.y * (2 * (((v[0][i] & 2) > 0) ? 1 : 0) - 1)),
                            c.z + (r.z * (2 * (((v[0][i] & 4) > 0) ? 1 : 0) - 1))),

appears to fix it.

**Comment by pansapiens** [comment]
Thanks - fixed !

**Comment by omgwtfgames** [comment]
Thanks - fixed !
